version: "3.8"

services:
  web:
    build:
      context: ./docker/php
    container_name: php-web
    ports:
      - "8000:80"   
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped
